// File generated by FlutterFire CLI.
// IMPORTANT: Run `flutterfire configure` to generate actual Firebase configuration
// This is a placeholder to allow the app to compile.
// To configure Firebase properly, run:
//   1. npm install -g firebase-tools
//   2. firebase login
//   3. dart pub global activate flutterfire_cli
//   4. flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // PLACEHOLDER - Replace with your actual Firebase project configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEMO-web-api-key-placeholder',
    appId: '1:1234567890:web:demo',
    messagingSenderId: '1234567890',
    projectId: 'demo-project-id',
    authDomain: 'demo-project-id.firebaseapp.com',
    storageBucket: 'demo-project-id.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEMO-android-api-key-placeholder',
    appId: '1:1234567890:android:demo',
    messagingSenderId: '1234567890',
    projectId: 'demo-project-id',
    storageBucket: 'demo-project-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEMO-ios-api-key-placeholder',
    appId: '1:1234567890:ios:demo',
    messagingSenderId: '1234567890',
    projectId: 'demo-project-id',
    storageBucket: 'demo-project-id.firebasestorage.app',
    iosBundleId: 'com.example.atelier1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEMO-macos-api-key-placeholder',
    appId: '1:1234567890:macos:demo',
    messagingSenderId: '1234567890',
    projectId: 'demo-project-id',
    storageBucket: 'demo-project-id.firebasestorage.app',
    iosBundleId: 'com.example.atelier1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEMO-windows-api-key-placeholder',
    appId: '1:1234567890:windows:demo',
    messagingSenderId: '1234567890',
    projectId: 'demo-project-id',
    authDomain: 'demo-project-id.firebaseapp.com',
    storageBucket: 'demo-project-id.firebasestorage.app',
  );
}
